/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oldsportcompanybank_client;

/**
 *
 * @author  Old Sport Company
 */
public class c extends javax.swing.JFrame {

    /**
     * Creates new form c
     */
    public c() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Interfaccia = new javax.swing.JPanel();
        Data = new javax.swing.JLabel();
        Nominativi = new javax.swing.JLabel();
        IBAN = new javax.swing.JLabel();
        Bonifici = new javax.swing.JPanel();
        Versamento = new javax.swing.JButton();
        Trasferimento = new javax.swing.JButton();
        NumeroIBAN = new javax.swing.JTextField();
        Intestatario = new javax.swing.JTextField();
        NomeMittente = new javax.swing.JTextField();
        SommaBonifico = new javax.swing.JTextField();
        NumeroCarta = new javax.swing.JTextField();
        Somma = new javax.swing.JTextField();
        ScadenzaCarta = new javax.swing.JTextField();
        CVC_CVV = new javax.swing.JTextField();
        Transazioni = new javax.swing.JPanel();
        TransazioneImporto = new javax.swing.JLabel();
        TransazioneData = new javax.swing.JLabel();
        TransazioneDettagli = new javax.swing.JLabel();
        Saldo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Versamento2 = new javax.swing.JTextField();
        Versamento4 = new javax.swing.JTextField();
        Versamento5 = new javax.swing.JTextField();
        Versamento3 = new javax.swing.JTextField();
        Versamento1 = new javax.swing.JTextField();
        Versamento6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        Data1 = new javax.swing.JTextField();
        Data3 = new javax.swing.JTextField();
        Importo4 = new javax.swing.JTextField();
        Importo3 = new javax.swing.JTextField();
        Importo1 = new javax.swing.JTextField();
        Importo2 = new javax.swing.JTextField();
        Data2 = new javax.swing.JTextField();
        Data4 = new javax.swing.JTextField();
        Data5 = new javax.swing.JTextField();
        Importo5 = new javax.swing.JTextField();
        Importo6 = new javax.swing.JTextField();
        Data6 = new javax.swing.JTextField();
        Data7 = new javax.swing.JTextField();
        Importo7 = new javax.swing.JTextField();
        Menu = new javax.swing.JMenuBar();
        Termina = new javax.swing.JMenu();
        Impostazioni = new javax.swing.JMenu();
        Help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Data.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Nominativi.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Nominativi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        IBAN.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        IBAN.setToolTipText("");
        IBAN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Bonifici.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Versamento.setText("Versamento");
        Versamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VersamentoActionPerformed(evt);
            }
        });

        Trasferimento.setText("Trasferimento");
        Trasferimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrasferimentoActionPerformed(evt);
            }
        });

        NumeroIBAN.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        NumeroIBAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroIBANActionPerformed(evt);
            }
        });

        Intestatario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        NomeMittente.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        SommaBonifico.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        NumeroCarta.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        NumeroCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroCartaActionPerformed(evt);
            }
        });

        Somma.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        ScadenzaCarta.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        CVC_CVV.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        javax.swing.GroupLayout BonificiLayout = new javax.swing.GroupLayout(Bonifici);
        Bonifici.setLayout(BonificiLayout);
        BonificiLayout.setHorizontalGroup(
            BonificiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BonificiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(BonificiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CVC_CVV, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScadenzaCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Somma, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SommaBonifico, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeMittente, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Intestatario, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BonificiLayout.createSequentialGroup()
                        .addGroup(BonificiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Versamento, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Trasferimento, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        BonificiLayout.setVerticalGroup(
            BonificiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BonificiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeMittente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumeroIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SommaBonifico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Intestatario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Versamento)
                .addGap(25, 25, 25)
                .addComponent(NumeroCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Somma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScadenzaCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CVC_CVV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Trasferimento)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Transazioni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TransazioneImporto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TransazioneImporto.setText(" IMPORTO");
        TransazioneImporto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TransazioneData.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TransazioneData.setText("   DATA");
        TransazioneData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TransazioneDettagli.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TransazioneDettagli.setText("   VERSAMENTI");
        TransazioneDettagli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Saldo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Saldo.setText("SALDO");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Versamento2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Versamento4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Versamento5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Versamento3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Versamento1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Versamento6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jTextField7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Data1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Data3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Importo4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Importo3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Importo1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Importo2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Data2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Data4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Data5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Importo5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Importo6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Data6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Data7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Importo7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        javax.swing.GroupLayout TransazioniLayout = new javax.swing.GroupLayout(Transazioni);
        Transazioni.setLayout(TransazioniLayout);
        TransazioniLayout.setHorizontalGroup(
            TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransazioniLayout.createSequentialGroup()
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Versamento5)
                    .addComponent(Versamento4)
                    .addComponent(Versamento3)
                    .addComponent(Versamento2)
                    .addComponent(Versamento1)
                    .addComponent(TransazioneDettagli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addComponent(Versamento6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransazioniLayout.createSequentialGroup()
                        .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Data4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TransazioneData, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(Data1)
                                .addComponent(Data3)
                                .addComponent(Data2))
                            .addComponent(Data7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TransazioneImporto, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Importo3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Importo1)
                                .addComponent(Importo2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Importo4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(Importo7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TransazioniLayout.createSequentialGroup()
                        .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Data5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Data6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Importo6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Importo5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        TransazioniLayout.setVerticalGroup(
            TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransazioniLayout.createSequentialGroup()
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TransazioneImporto, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(TransazioneDettagli, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(TransazioneData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Versamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Importo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Versamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Importo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Versamento3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Importo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Versamento4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Importo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Versamento5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Importo5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Versamento6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Importo6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Importo7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Saldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout InterfacciaLayout = new javax.swing.GroupLayout(Interfaccia);
        Interfaccia.setLayout(InterfacciaLayout);
        InterfacciaLayout.setHorizontalGroup(
            InterfacciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfacciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InterfacciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterfacciaLayout.createSequentialGroup()
                        .addComponent(IBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(Nominativi, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)
                        .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InterfacciaLayout.createSequentialGroup()
                        .addComponent(Bonifici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Transazioni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        InterfacciaLayout.setVerticalGroup(
            InterfacciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfacciaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(InterfacciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterfacciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Nominativi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InterfacciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bonifici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Transazioni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Termina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Termina.setText("Termina");
        Termina.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Menu.add(Termina);

        Impostazioni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Impostazioni.setText("Impostazioni");
        Impostazioni.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Menu.add(Impostazioni);

        Help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Help.setText("Help (?)");
        Help.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Menu.add(Help);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Interfaccia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Interfaccia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeroCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCartaActionPerformed

    private void NumeroIBANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroIBANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroIBANActionPerformed

    private void TrasferimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrasferimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrasferimentoActionPerformed

    private void VersamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VersamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VersamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(c.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(c.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(c.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(c.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new c().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bonifici;
    private javax.swing.JTextField CVC_CVV;
    private javax.swing.JLabel Data;
    private javax.swing.JTextField Data1;
    private javax.swing.JTextField Data2;
    private javax.swing.JTextField Data3;
    private javax.swing.JTextField Data4;
    private javax.swing.JTextField Data5;
    private javax.swing.JTextField Data6;
    private javax.swing.JTextField Data7;
    private javax.swing.JMenu Help;
    private javax.swing.JLabel IBAN;
    private javax.swing.JTextField Importo1;
    private javax.swing.JTextField Importo2;
    private javax.swing.JTextField Importo3;
    private javax.swing.JTextField Importo4;
    private javax.swing.JTextField Importo5;
    private javax.swing.JTextField Importo6;
    private javax.swing.JTextField Importo7;
    private javax.swing.JMenu Impostazioni;
    private javax.swing.JPanel Interfaccia;
    private javax.swing.JTextField Intestatario;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JTextField NomeMittente;
    private javax.swing.JLabel Nominativi;
    private javax.swing.JTextField NumeroCarta;
    private javax.swing.JTextField NumeroIBAN;
    private javax.swing.JLabel Saldo;
    private javax.swing.JTextField ScadenzaCarta;
    private javax.swing.JTextField Somma;
    private javax.swing.JTextField SommaBonifico;
    private javax.swing.JMenu Termina;
    private javax.swing.JLabel TransazioneData;
    private javax.swing.JLabel TransazioneDettagli;
    private javax.swing.JLabel TransazioneImporto;
    private javax.swing.JPanel Transazioni;
    private javax.swing.JButton Trasferimento;
    private javax.swing.JButton Versamento;
    private javax.swing.JTextField Versamento1;
    private javax.swing.JTextField Versamento2;
    private javax.swing.JTextField Versamento3;
    private javax.swing.JTextField Versamento4;
    private javax.swing.JTextField Versamento5;
    private javax.swing.JTextField Versamento6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
