/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oldsportcompanybank_client;

/**
 *
 * @author Old Sport Company
 */
public class Resgistrazione extends javax.swing.JFrame {

    /**
     * Creates new form Resgistrazione
     */
    public Resgistrazione() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registrazione = new javax.swing.JPanel();
        Label_mail = new javax.swing.JLabel();
        Label_password = new javax.swing.JLabel();
        Label_confermaMail = new javax.swing.JLabel();
        Label_CF = new javax.swing.JLabel();
        Label_confermaPass = new javax.swing.JLabel();
        Label_luogoNascita = new javax.swing.JLabel();
        Label_dataNascita = new javax.swing.JLabel();
        Label_nome = new javax.swing.JLabel();
        Label_indirizzo = new javax.swing.JLabel();
        Label_cognome = new javax.swing.JLabel();
        Label_CAP = new javax.swing.JLabel();
        Registrazione_mail = new javax.swing.JTextField();
        Registrazione_CAP = new javax.swing.JTextField();
        Label_provincia = new javax.swing.JLabel();
        Label_citta = new javax.swing.JLabel();
        Label_cellulare = new javax.swing.JLabel();
        Registrazione_password = new javax.swing.JTextField();
        Registrazione_CF = new javax.swing.JTextField();
        Registrazione_confermaMail = new javax.swing.JTextField();
        Registrazione_nome = new javax.swing.JTextField();
        Registrazione_confermaPass = new javax.swing.JTextField();
        Registrazione_cognome = new javax.swing.JTextField();
        Registrazione_giono = new javax.swing.JTextField();
        Registrazione_nascita = new javax.swing.JTextField();
        Registrazione_provincia = new javax.swing.JTextField();
        Registrazione_indirizzo = new javax.swing.JTextField();
        Registrazione_citta = new javax.swing.JTextField();
        Registrazione_cellulare = new javax.swing.JTextField();
        Registrazione_mese = new javax.swing.JTextField();
        Registrazione_anno = new javax.swing.JTextField();
        Button_conferma = new javax.swing.JButton();
        Button_annulla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_mail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_mail.setText("E-mail:");

        Label_password.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_password.setText("Password:");

        Label_confermaMail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_confermaMail.setText("Conferma E-mail:");

        Label_CF.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_CF.setText("Codice fiscale:");

        Label_confermaPass.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_confermaPass.setText("Conferma Password:");

        Label_luogoNascita.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_luogoNascita.setText("Luogo di nascita:");
        Label_luogoNascita.setToolTipText("");

        Label_dataNascita.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_dataNascita.setText("Data di nascita:");

        Label_nome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_nome.setText("Nome:");

        Label_indirizzo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_indirizzo.setText("Indirizzo:");

        Label_cognome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_cognome.setText("Cognome:");

        Label_CAP.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_CAP.setText("CAP:");

        Registrazione_mail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_CAP.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Label_provincia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_provincia.setText("Provincia:");

        Label_citta.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_citta.setText("Città:");

        Label_cellulare.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_cellulare.setText("Cellulare:");

        Registrazione_password.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_CF.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_confermaMail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_nome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_confermaPass.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_cognome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_giono.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Registrazione_giono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ì(evt);
            }
        });

        Registrazione_nascita.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_provincia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_indirizzo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_citta.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_cellulare.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_mese.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Registrazione_anno.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        Button_conferma.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Button_conferma.setText("Conferma");

        Button_annulla.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Button_annulla.setText("Annulla");

        javax.swing.GroupLayout RegistrazioneLayout = new javax.swing.GroupLayout(Registrazione);
        Registrazione.setLayout(RegistrazioneLayout);
        RegistrazioneLayout.setHorizontalGroup(
            RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrazioneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_mail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_mail))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_confermaMail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_confermaMail))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_password))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_confermaPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_confermaPass))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_CF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_CF))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_nome))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_cognome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_cognome))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_dataNascita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_giono, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_mese, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_anno))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_luogoNascita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_nascita))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_indirizzo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_indirizzo))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_citta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_citta))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_cellulare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_cellulare))
                    .addGroup(RegistrazioneLayout.createSequentialGroup()
                        .addComponent(Label_CAP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_CAP)
                        .addGap(18, 18, 18)
                        .addComponent(Label_provincia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrazione_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(RegistrazioneLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Button_conferma)
                .addGap(18, 18, 18)
                .addComponent(Button_annulla)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        RegistrazioneLayout.setVerticalGroup(
            RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrazioneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_mail)
                    .addComponent(Registrazione_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_confermaMail)
                    .addComponent(Registrazione_confermaMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_password)
                    .addComponent(Registrazione_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_confermaPass)
                    .addComponent(Registrazione_confermaPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CF)
                    .addComponent(Registrazione_CF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_nome)
                    .addComponent(Registrazione_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_cognome)
                    .addComponent(Registrazione_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_dataNascita)
                    .addComponent(Registrazione_giono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registrazione_anno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registrazione_mese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_luogoNascita)
                    .addComponent(Registrazione_nascita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_indirizzo)
                    .addComponent(Registrazione_indirizzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CAP)
                    .addComponent(Registrazione_CAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_provincia)
                    .addComponent(Registrazione_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_citta)
                    .addComponent(Registrazione_citta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_cellulare)
                    .addComponent(Registrazione_cellulare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_annulla)
                    .addComponent(Button_conferma))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registrazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registrazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ì(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ì
        // TODO add your handling code here:
    }//GEN-LAST:event_ì

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resgistrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resgistrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resgistrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resgistrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resgistrazione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_annulla;
    private javax.swing.JButton Button_conferma;
    private javax.swing.JLabel Label_CAP;
    private javax.swing.JLabel Label_CF;
    private javax.swing.JLabel Label_cellulare;
    private javax.swing.JLabel Label_citta;
    private javax.swing.JLabel Label_cognome;
    private javax.swing.JLabel Label_confermaMail;
    private javax.swing.JLabel Label_confermaPass;
    private javax.swing.JLabel Label_dataNascita;
    private javax.swing.JLabel Label_indirizzo;
    private javax.swing.JLabel Label_luogoNascita;
    private javax.swing.JLabel Label_mail;
    private javax.swing.JLabel Label_nome;
    private javax.swing.JLabel Label_password;
    private javax.swing.JLabel Label_provincia;
    private javax.swing.JPanel Registrazione;
    private javax.swing.JTextField Registrazione_CAP;
    private javax.swing.JTextField Registrazione_CF;
    private javax.swing.JTextField Registrazione_anno;
    private javax.swing.JTextField Registrazione_cellulare;
    private javax.swing.JTextField Registrazione_citta;
    private javax.swing.JTextField Registrazione_cognome;
    private javax.swing.JTextField Registrazione_confermaMail;
    private javax.swing.JTextField Registrazione_confermaPass;
    private javax.swing.JTextField Registrazione_giono;
    private javax.swing.JTextField Registrazione_indirizzo;
    private javax.swing.JTextField Registrazione_mail;
    private javax.swing.JTextField Registrazione_mese;
    private javax.swing.JTextField Registrazione_nascita;
    private javax.swing.JTextField Registrazione_nome;
    private javax.swing.JTextField Registrazione_password;
    private javax.swing.JTextField Registrazione_provincia;
    // End of variables declaration//GEN-END:variables
}
